export const ERROR_CODE = {
  BAD_REQUEST: "BAD_REQUEST",
  ADDRESS_LIMIT_REACHED: "ADDRESS_LIMIT_REACHED",
  CATEGORY_CYCLE: "CATEGORY_CYCLE",
  CATEGORY_IN_USE: "CATEGORY_IN_USE",
  CONFLICT: "CONFLICT",
  COUPON_CODE_ALREADY_EXISTS: "COUPON_CODE_ALREADY_EXISTS",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  FORBIDDEN: "FORBIDDEN",
  INVALID_INVENTORY_OPERATION: "INVALID_INVENTORY_OPERATION",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_PICKUP_CONFIGURATION: "INVALID_PICKUP_CONFIGURATION",
  INVALID_PROVIDER_OPTION: "INVALID_PROVIDER_OPTION",
  INVALID_PROVIDER_STATUS: "INVALID_PROVIDER_STATUS",
  INVALID_SHIPPING_METHOD: "INVALID_SHIPPING_METHOD",
  INVALID_WEIGHT_RANGE: "INVALID_WEIGHT_RANGE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN",
  NOT_FOUND: "NOT_FOUND",
  OUT_OF_STOCK: "OUT_OF_STOCK",
  PICKUP_SCHEDULE_OVERLAP: "PICKUP_SCHEDULE_OVERLAP",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  SKU_CONFLICT: "SKU_CONFLICT",
  SLUG_CONFLICT: "SLUG_CONFLICT",
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  WISHLIST_ITEM_EXISTS: "WISHLIST_ITEM_EXISTS",
  WISHLIST_ITEM_NOT_FOUND: "WISHLIST_ITEM_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];

export interface ApiFieldIssue {
  code: string;
  field: string;
  message: string;
}

export interface ApiErrorResponse {
  code: ErrorCode;
  issues?: readonly ApiFieldIssue[];
  message: string;
  ok: false;
}
