export const ERROR_CODE = {
  BAD_REQUEST: "BAD_REQUEST",
  CATEGORY_CYCLE: "CATEGORY_CYCLE",
  CATEGORY_IN_USE: "CATEGORY_IN_USE",
  CONFLICT: "CONFLICT",
  FORBIDDEN: "FORBIDDEN",
  INVALID_INVENTORY_OPERATION: "INVALID_INVENTORY_OPERATION",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  OUT_OF_STOCK: "OUT_OF_STOCK",
  RATE_LIMITED: "RATE_LIMITED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  SKU_CONFLICT: "SKU_CONFLICT",
  SLUG_CONFLICT: "SLUG_CONFLICT",
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];

export interface ApiFieldIssue {
  code: string;
  field: string;
  message: string;
}

export interface ApiErrorResponse {
  code: ErrorCode;
  issues?: readonly ApiFieldIssue[];
  message: string;
  ok: false;
}
