import { z } from "zod";
import { CustomersApiError, FetchCustomersApiClient, type CustomersApiClient } from "./client";
import { customersApiConfig } from "./customers-api-config";
import { createCustomerInputSchema, customerDetailResponseSchema, customerEmailAvailabilityResponseSchema, customerEmailAvailabilitySchema, customerIdSchema, customerListQuerySchema, customerListResponseSchema, customerResponseSchema, normalizeCustomerInput, toValidationIssues, updateCustomerInputSchema, updateCustomerNotesSchema } from "./contracts";
import type { CustomersRepository } from "./repository";
import type { CreateCustomerInput, Customer, CustomerDetailResult, CustomerListQuery, CustomerListResult, CustomerMutationResult, UpdateCustomerInput } from "./types";
import { MockCustomersRepository } from "./mock-customers.repository";

export class ApiCustomersRepository implements CustomersRepository {
  readonly source = "api" as const;
  constructor(private readonly client: CustomersApiClient = new FetchCustomersApiClient(), private readonly fallback: CustomersRepository = new MockCustomersRepository(), private readonly fallbackToMock = customersApiConfig.fallbackToMock) {}

  list(query: CustomerListQuery = {}): Promise<CustomerListResult> { const parsed = parse(customerListQuerySchema, query, "The customer list query is invalid."); return this.recover(() => this.client.get<unknown>(withQuery(customersApiConfig.endpoints.collection, parsed)).then(mapList), () => this.fallback.list(parsed)); }
  getById(id: string): Promise<CustomerDetailResult> { const customerId = parse(customerIdSchema, id, "The customer identifier is invalid."); return this.recover(() => this.client.get<unknown>(`${customersApiConfig.endpoints.collection}/${encodeURIComponent(customerId)}`).then(mapDetail), () => this.fallback.getById(customerId)); }
  create(input: CreateCustomerInput): Promise<CustomerMutationResult> { const payload = parse(createCustomerInputSchema, normalizeCustomerInput(input), "The customer payload is invalid."); return this.recover(() => this.client.post<unknown>(customersApiConfig.endpoints.collection, payload).then(mutation), () => this.fallback.create(payload)); }
  update(id: string, input: UpdateCustomerInput): Promise<CustomerMutationResult> { const customerId = parse(customerIdSchema, id, "The customer identifier is invalid."); const payload = parse(updateCustomerInputSchema, normalizeCustomerInput(input), "The customer payload is invalid."); return this.recover(() => this.client.put<unknown>(`${customersApiConfig.endpoints.collection}/${encodeURIComponent(customerId)}`, payload).then(mutation), () => this.fallback.update(customerId, payload)); }
  updateNotes(id: string, notes: string): Promise<CustomerMutationResult> { const customerId = parse(customerIdSchema, id, "The customer identifier is invalid."); const payload = parse(updateCustomerNotesSchema, { notes }, "The customer notes are invalid."); return this.recover(() => this.client.patch<unknown>(`${customersApiConfig.endpoints.collection}/${encodeURIComponent(customerId)}/notes`, payload).then(mutation), () => this.fallback.updateNotes(customerId, payload.notes)); }
  anonymize(id: string): Promise<CustomerMutationResult> { const customerId = parse(customerIdSchema, id, "The customer identifier is invalid."); return this.recover(() => this.client.post<unknown>(`${customersApiConfig.endpoints.collection}/${encodeURIComponent(customerId)}/anonymize`, {}).then(mutation), () => this.fallback.anonymize(customerId)); }
  exportCsv(query: CustomerListQuery = {}): Promise<string> { const parsed = parse(customerListQuerySchema, query, "The customer list query is invalid."); return this.recover(() => this.client.getText(withQuery(customersApiConfig.endpoints.export, parsed)), () => this.fallback.exportCsv(parsed)); }
  exportCustomerDetailCsv(id: string): Promise<string> { const customerId = parse(customerIdSchema, id, "The customer identifier is invalid."); return this.recover(() => this.client.getText(`${customersApiConfig.endpoints.collection}/${encodeURIComponent(customerId)}/export`), () => this.fallback.exportCustomerDetailCsv(customerId)); }
  isEmailAvailable(email: string, excludeCustomerId?: string): Promise<boolean> { const parsed = parse(customerEmailAvailabilitySchema, { email, ...(excludeCustomerId ? { excludeCustomerId } : {}) }, "The customer email is invalid."); const query = new URLSearchParams({ email: parsed.email }); if (parsed.excludeCustomerId) query.set("excludeCustomerId", parsed.excludeCustomerId); return this.recover(() => this.client.get<unknown>(`${customersApiConfig.endpoints.availability}?${query}`).then((value) => response(customerEmailAvailabilityResponseSchema, value).available), () => this.fallback.isEmailAvailable(parsed.email, parsed.excludeCustomerId)); }

  private async recover<T>(operation: () => Promise<T>, fallback: () => Promise<T>): Promise<T> { try { return await operation(); } catch (error) { if (this.fallbackToMock && isNetworkError(error)) return fallback(); throw error; } }
}

export const getAdminCustomersRepository = (client?: CustomersApiClient): ApiCustomersRepository => new ApiCustomersRepository(client);
function mapList(value: unknown): CustomerListResult { const parsed = response(customerListResponseSchema, value); return { items: parsed.items.map(mapCustomer), limit: parsed.limit, page: parsed.page, total: parsed.total, totalPages: parsed.totalPages }; }
function mapDetail(value: unknown): CustomerDetailResult { const parsed = response(customerDetailResponseSchema, value); const { summary, ...customer } = parsed; return { ...mapCustomer(customer), summary: { ...summary, ...(summary.lastOrder ? { lastOrder: { ...summary.lastOrder } } : {}) } }; }
function mutation(value: unknown): CustomerMutationResult { const customer = mapCustomer(value); return { ok: true, customer, customerId: customer.id }; }
function mapCustomer(value: unknown): Customer { const parsed = response(customerResponseSchema, value); return { id: parsed.id, fullName: parsed.fullName, email: parsed.email, firstInteractionDate: parsed.firstInteractionDate, isAnonymized: parsed.isAnonymized, createdAt: parsed.createdAt, updatedAt: parsed.updatedAt, tags: [...parsed.tags], ...(parsed.address ? { address: { ...parsed.address } } : {}), ...(parsed.phone ? { phone: parsed.phone } : {}), ...(parsed.dniOrCuil ? { dniOrCuil: parsed.dniOrCuil } : {}), ...(parsed.notes ? { notes: parsed.notes } : {}), ...(parsed.summary ? { summary: { ...parsed.summary, ...(parsed.summary.lastOrder ? { lastOrder: { ...parsed.summary.lastOrder } } : {}) } } : {}) }; }
function response<T>(schema: z.ZodType<T>, value: unknown): T { const unwrapped = isRecord(value) && value.ok === true && "data" in value ? value.data : value; if (isRecord(unwrapped) && unwrapped.ok === false) throw new CustomersApiError({ code: String(unwrapped.code ?? "CUSTOMERS_API_ERROR"), message: String(unwrapped.message ?? "The customers request failed."), status: 400 }); const parsed = schema.safeParse(unwrapped); if (parsed.success) return parsed.data; throw new CustomersApiError({ code: "CUSTOMERS_API_INVALID_RESPONSE", issues: toValidationIssues(parsed.error), message: "The customers API returned an invalid response.", status: 502 }); }
function parse<T>(schema: z.ZodType<T>, value: unknown, message: string): T { const result = schema.safeParse(value); if (result.success) return result.data; throw new CustomersApiError({ code: "VALIDATION_ERROR", issues: toValidationIssues(result.error), message, status: 400 }); }
function withQuery(path: string, query: CustomerListQuery): string { const params = new URLSearchParams(); for (const [key, value] of Object.entries(query)) if (value !== undefined) params.set(key, String(value)); const serialized = params.toString(); return serialized ? `${path}?${serialized}` : path; }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function isNetworkError(error: unknown): boolean { return error instanceof CustomersApiError ? error.status === 503 || error.code === "CUSTOMERS_API_UNAVAILABLE" : error instanceof TypeError || (error instanceof Error && /fetch|network|offline/i.test(error.message)); }
